spring:
  data:
    mongodb:
      database: userdb
      auto-index-creation: false
      password: password
      username: julia
      authentication-database: admin
      port: 27017
      host: localhost
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              org.springframework.data.mongodb.core.MongoTemplate: DEBUG